### ISSUE TITLE
Ready-to-use Docker Image

### ISSUE THREAD

**Issue by m6121** [audiolabs/webMUSHRA#68]
Hi,

thanks a lot for this awesome tool and the provision of a docker specification. To further ease use of the tool, would it be possible to use Github-CI for building the docker image and pushing the image at e.g. Docker Hub? This would very much increase usability as only the `docker-compose.yml` needs to be configured and the image would simply be downloaded.

Many thanks in advance.
Max

**Comment by faroit** [comment]
@m6121 sure, thats a great idea. I can host the image under my name space. Can you check if the docker-compose is up-to-date and runs fine?

**Comment by m6121** [comment]
Hi @faroit,

thanks for the fast response. This sounds great.
Yes, the latest [docker-compose](https://github.com/audiolabs/webMUSHRA/blob/bcf9c10e4d3493d0bf8f2ed6d8c8c5d7e5f15278/docker-compose.yml) is working fine. Maybe some comments could be added to explain the configuration a little, e.g. 

```yml
version: '2'
services:
  webmushra:
    image: webmushra
    volumes:
      # configure the host directory that should be used for the results, e.g.
      #
      #    - /home/jdoe/experiments/results:/var/www/html/results
      #
      # if the host directory /home/jdoe/experiments/results is used
      # for Windows hosts, an example might be as follows:
      #
      #    - /c/experiments/results:/var/www/html/results
      #
      # NOTE: this directory must be writable by the UID=33 (www-data) of the
      # docker image
      - ./results:/var/www/html/results

      # configure the host directory where the configuration can be found
      - ./configs:/var/www/html/configs
    ports:
      - "8000:80"
```
