### ISSUE TITLE
Results were not saved in 'results' folder after "send result" button

### ISSUE THREAD

**Issue by jyn282** [audiolabs/webMUSHRA#74]
Hi, thank you for this amazing repository. :)

I've set up webMUSHRA using Docker as written in README.md.
After that, I tried complete.yaml. 
The test worked well, but when I pressed the "send result" button on the last page, an error occurred as follows.

"An error occured while sending your data to the server! Please contact the. experimenter."

Also, there was no new folder in the results folder. 

Could you please check on this issue?

**Comment by faroit** [comment]
@jyn282 did you mount `results ` and `configs` when launching the docker container?

**Comment by jyn282** [comment]
yes, I think so, I didn't change docker-compose.yml nor DockerFile. 
That means ```results``` and ```configs``` folers were mounted to
```/var/www/html/results ``` and ```/var/www/html/config ```  ,  is that right?
I made two folders in the above paths and also checked file authority.

**Comment by faroit** [comment]
@jyn282 please show your docker command here

**Comment by jyn282** [comment]
Thank you for the quick replay. 

I tried as follows.

Dockerfile
```
FROM php:7.0-apache
COPY ./ /var/www/html/
```

docker-compose.yml
```
version: '2'
services:
  webmushra:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/var/www/html/results
      - ./configs:/var/www/html/configs
    ports:
      - "8000:80"
```

Then, I build and run docker container as follows.
```
docker-compose -f docker-compose.yml build
```
```
docker-compose -f docker-compose.yml up
```

I could change YAML file in ```configs``` folder on the fly but couldn't get result csv files.
